version: '3.9'

services:  
  mongo-service:
    build:
      context: ./MongoDB
      dockerfile: Dockerfile  
    container_name: mongodb_container
    networks:
      custom_network:
        ipv4_address: 192.168.1.2
    ports:
      - "27017:27017"

  react-app-service:
    build:
      context: ./FrontendApplication  
      dockerfile: Dockerfile  
    container_name: container_of_react_app
    ports:
      - "80:80"
    networks:
      custom_network:
        ipv4_address: 192.168.1.3
    volumes:
      - shared-volume:/shared-data

  flask-app-service:
    build:
      context: ./QuoteService  
      dockerfile: Dockerfile  
    container_name: flask_app_container
    ports:
      - "5000:5000"
    networks:
      custom_network:
        ipv4_address: 192.168.1.4
    volumes:
      - shared-volume:/shared-data

  redis-service:
    image: redis:latest
    container_name: container_of_redis
    ports:
      - "6379:6379"
    networks:
      custom_network:
        ipv4_address: 192.168.1.5

  api-gateway-service:
    build:
      context: ./ApiGateway 
      dockerfile: Dockerfile  
    container_name: container_of_api_gateway
    ports:
      - "3000:3000"
    networks:
      custom_network:
        ipv4_address: 192.168.1.6
    volumes:
      - shared-volume:/shared-data

networks:
  custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

volumes:
  shared-volume:
